### ISSUE TITLE
Improve logic for en_US

### ISSUE THREAD

**Issue by afercia** [swissspidy/preferred-languages#16]
Seems to me there's an edge case when `en_US` is set as first preferred language. To reproduce, set the Site Language to: en_US as first locale and another language as second locale:

<img width="758" alt="screen shot 2017-05-21 at 17 03 52" src="https://cloud.githubusercontent.com/assets/1682452/26285037/d6154b5a-3e47-11e7-9430-fbb5d8b5f100.png">

At this point, my frontend is displayed in Italian. This would happen also in other cases, for example:
1. en_US
2. en_GB

If I'm not wrong, `preferred_languages_load_textdomain_mofile()` returns the first locale (or better, uses the .mo files for the first locale) that has readable .mo files. The point is, there are no `en_US` .mo files so it's using the Italian ones?

**Comment by swissspidy** [comment]
> The point is, there are no `en_US` .mo files so it's using the Italian ones?

That's correct, yes. However, there _could_ be, e.g. when manually added by someone to override some strings.

Note that it doesn't really matter where `en_US` is in the list.

I've been thinking about that situation a few times and I'm not sure yet how this should be handled.

One option would be to modify `preferred_languages_load_textdomain_mofile()` so it returns true for `en_US`, but then it wouldn't make sense to have anything after en_US, because it would never be loaded.

Another option is to disallow selecting en_US in the drop down. Then, when you remove all locales from the list, there would be some kind of note like "Nothing set, falling back to English (US)".

Or, just leave a note at the top that en_US always comes last because it's the base language.

**Comment by afercia** [comment]
Hm maybe the UI should reflect the functionality then, I mean en_US should always be displayed as last language in the list and users shouldn't be allowed to move it? And yep, a note explaining how it works and that en_US is always the last fallback? Not sure, just throwing ideas out there.

**Comment by swissspidy** [comment]
> Another option is to disallow selecting en_US in the drop down. Then, when you remove all locales from the list, there would be some kind of note like "Nothing set, falling back to English (US)".

Here's how it could look like:

<img width="729" alt="screen shot 2017-10-01 at 18 18 37" src="https://user-images.githubusercontent.com/841956/31056656-67d9ec6c-a6d5-11e7-8649-aeebcdd842ee.png">
<img width="724" alt="screen shot 2017-10-01 at 18 19 54" src="https://user-images.githubusercontent.com/841956/31056657-67dd5d8e-a6d5-11e7-9238-b475b2ed6596.png">

> Or, just leave a note at the top that en_US always comes last because it's the base language.

> Hm maybe the UI should reflect the functionality then, I mean en_US should always be displayed as last language in the list and users shouldn't be allowed to move it? And yep, a note explaining how it works and that en_US is always the last fallback?

That's already the behaviour today. I don't think it needs an explanation now.

**Comment by swissspidy** [comment]
I just added such a note like in the screenshot, but it'd need an a11y review. Right now the message is just a `<li>` in that listbox. Some proper declaration or announcement to assistive technologies would be benificial.

**Comment by swissspidy** [comment]
Closing for now.
