### ISSUE TITLE
Can't add an already installed language (English US)

### ISSUE THREAD

**Issue by zu** [swissspidy/preferred-languages#28]
![preferred-languages](https://user-images.githubusercontent.com/147629/32615969-70047474-c571-11e7-89ea-831f73fe3537.png)

I only see available languages but not the already installed ones so I can't add English US (which I wanted to make it the first for a test in this case)

**Comment by swissspidy** [comment]
I purposely left out `English (US)` from the list of available languages in this list because that's the language WordPress is in by default. If you want that language, just remove all languages from the list.

Now that I think about it, when the site language is German, a user might still want to set English as their language…
