### ISSUE TITLE
Translations not downloaded

### ISSUE THREAD

**Issue by grappler** [swissspidy/preferred-languages#34]
I have set up my site with multiple languages.

![image](https://user-images.githubusercontent.com/1785641/42449572-730b7d7e-8381-11e8-8781-6cb67f9bf23b.png)

I did not have `de_CH_informal` install. When checking the updates page there were no updates. After running `wp language core install de_CH_informal` updates started to show for `de_CH_informal`.

**Comment by nickw108** [comment]
Not sure if this is related to 4.9.7 de_CH https://de-ch.wordpress.org/releases/ being released only yesterday? There were a couple of strings missing, which I wasn't aware of until yesterday 🤓

**Comment by swissspidy** [comment]
I just tested adding de_CH_* locally and they all were installed just fine after updating the settings.

WordPress not showing any updates is not something this plugin is dealing with.

Can you please try it again?

**Comment by grappler** [comment]
This is still an issue. The problem is that only the first language on the list is downloaded. The others are ignored.

You can test this by deleting all of the `de` translations and checking that now language is installed before you activate the plugin. If you set up the languages like I have in the screenshot above WP will only install the first in this case `de_CH`.

You can try it with other languages too.

**Comment by daveloodts** [comment]
Seeing this too as i'm start to test nl_nl and nl_be, delete the nl_be but can't get them back via the update dashboard

**Comment by swissspidy** [comment]
I still can't reproduce the settings part, neither in the site settings nor when editing a profile. What I did:

1. Remove all translation files
2. Clear preferred locales setting and save them.
3. Add a few locales and save them.
4. Notice how all translation files are downloaded.

When not all translations are downloaded, it's most likely because of an HTTP timeout or similar in the WordPress internals.

To account for this, I'm going to adjust the plugin in a way that you can just re-save the settings and the plugin will try to download the translations if they're not available yet. So if you update your settings and nothing happens, just press the update button once again.

Also, I think I'm going to add a small warning in that case, e.g. "Hey, your preferred locales are de_CH and de_DE, but they aren't installed. Please re-save your settings".

----

@daveloodts Good point regarding the updates screen! That indeed does only install one locale.

The tricky thing there is that WordPress only checks for updates for the current locale (i.e. the first one in the list).

I'll try to come up with a solution for this, but it's gonna be hacky as there aren't really any (good) hooks in the code for that kind of manipulation.

**Comment by swissspidy** [comment]
Created a new issue for the updates screen thing: #36.
