### ISSUE TITLE
Add caching to `preferred_languages_filter_gettext`

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/preferred-languages#675]
The function `preferred_languages_filter_gettext` is called 1.8k times on a FE request. Adding some check like this might improve performance. 

Stop `get_translations_for_domain` from being run by setting a flag in an static variable, so it is not run again.

**Comment by swissspidy** [comment]
Just adding some context:

`preferred_languages_filter_gettext` is hooked to the `gettext` filter, i.e. every translation call. So 1.8k calls sounds reasonable.

The `get_translations_for_domain` call should be very cheap, because that function is also called by WP right before the `gettext` filter, so the call in `preferred_languages_filter_gettext` should be super quick since all the just-in-time translation loading happens there already:

https://github.com/WordPress/wordpress-develop/blob/250250d35ede7402cf474a0f439d7f6c992dd7d7/src/wp-includes/l10n.php#L187-L199

https://github.com/WordPress/wordpress-develop/blob/250250d35ede7402cf474a0f439d7f6c992dd7d7/src/wp-includes/l10n.php#L1303-L1315

**Comment by spacedmonkey** [comment]
Would this be needed if this is core?

**Comment by swissspidy** [comment]
When merging this into core, this whole logic would probably move directly into `_load_textdomain_just_in_time()`
